# Generated by Django 5.1.2 on 2024-10-28 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15)),
                ('autor', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('tipo_locador', models.CharField(choices=[('F', 'FUNCIONARIO'), ('A', 'ALUNO')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('M', 'DIURNO'), ('T', 'VESPERTINO'), ('N', 'NOTURNO')], default='M', max_length=1)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.locador')),
            ],
        ),
    ]
